# Generated by Django 6.0.6 on 2026-06-18 09:26

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.avatar_upload_path),
        ),
    ]
