# Generated by Django 6.0.6 on 2026-06-18 11:14

import apps.users.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Username must be lowercase or underscore only.', regex='^[a-z_]+$'), apps.users.models.validate_username_not_forbidden], verbose_name='username'),
        ),
    ]
