# Generated by Django 6.0.6 on 2026-08-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_follow_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
